### ISSUE TITLE
Thread started by EMCRemapEvent gets stuck in infinite loop

### ISSUE THREAD

**Issue by TigerWalts** [Colton-Slayden/Auxilium-Equivalence#1]
Version: `1.12.2-1.2.1`

The **EMCMappingHand** class has an event handler that starts a thread with a while loop that may or may not exit. The while loop also contains no Thread.sleep() call so it ends up using 100% of a CPU core.

- https://github.com/Colton-Slayden/Auxilium-Equivalence/blob/484cb4316622ac20e69a702cfafa469e0e95b458/src/main/java/com/royalreject/auxiliumequivalence/handlers/EMCMappingHand.java#L40

**Comment by Colton-Slayden** [comment]
Removed in next update was not being used

**Comment by SteveKnowless** [comment]
I am also seeing a huge CPU increase when adding this mod to my server. Love this mod. Thank you for the time you put into it. Any ETA on the next release with the fixes? Thanks

**Comment by Colton-Slayden** [comment]
Should be fixed in 1.3.0 just uploaded to curseforge hopefully it helps, thanks for pointing this out to me.

**Comment by SteveKnowless** [comment]
Works perfect. Thank you
